### ISSUE TITLE
gzippo is not working with newest connect/express

### ISSUE THREAD

**Issue by Almad** [tomgco/gzippo#43]
staticSend has been extracted to separate library

**Comment by Almad** [comment]
(sorry for the first bad fix)

**Comment by uipoet** [comment]
+1. Updated to express 3.0.0beta6 and no worky.

**Comment by dhruv-bhatia** [comment]
`npm install connect@2.3.4` on the culprit project seems to fix this for me (I'm on the latest `Express@3.0RC1` with Gzippo working as expected).

**Comment by ryanseys** [comment]
Line 17 to 21

```
try {
    staticSend = require('connect').static.send; //returns undefined, doesn't throw an error
} catch (e) {
    staticSend = require('express').static.send;
}
```

require('connect').static.send; //returns undefined, so test for undefined
//or reorder so that staticSend = require('express').static.send; is tried before require('connect').static.send;

**Comment by serby** [comment]
+1 When will this be fixed?

**Comment by aozora** [comment]
+1 needed!

**Comment by reid-rigo** [comment]
my proposed solution is the following: https://github.com/rigoleto/gzippo/commit/555be0c418595700fe4c1b5b3fd7420a1be68e08

using connect as a dependency instead of the connect/express shenanigans, i rework the pass() function to simply pass non-eligible requests to the connect 2.5.x static middleware

**Comment by TravelingTechGuy** [comment]
Using Express3.0.0rc4, getting this error. I think it's the same others are experiencing, if not, I'll move to another issue:

/Users/Projects/tq/server/node_modules/gzippo/lib/staticGzip.js:108
            staticSend(req, res, next, o);
            ^
TypeError: undefined is not a function
    at pass (/Users/Projects/tq/server/node_modules/gzippo/lib/staticGzip.js:108:4)
    at module.exports (/Users/Projects/tq/server/node_modules/gzippo/lib/staticGzip.js:185:12)
    at Object.oncomplete (fs.js:297:15)

**Comment by tomgco** [comment]
Hello, 

First I would like to apologise my own lack on involvement in the project recently, I shouldn't of let the state of the module have no major development and I should of responded to these issues much sooner. The good news is that I am going to make a big push on getting as many fixes pushed out asap and possibly finish the major refactor I have been working on. 

Onto the issue:

I have just install the latest version of express on my machine: `express@3.0.0rc4` which is utilising `connect@2.4.4` and I am seeing the same issue, I am currently working on a fix at this moment and will update this issue as soon as I have made the merge and the deployment. 

Again I would like to apologise for my lack of response. 

~tomgco

**Comment by glynnbird** [comment]
I too have the same issue.

**Comment by tomgco** [comment]
0.2 has been released, hopefully this fixes the incompatibility. Let me know if any problems occur. I will keep this open just in case.
